name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-solidity:
    runs-on: ubuntu-22.04
    container:
      image: us-docker.pkg.dev/laguna-chain/laguna-chain/solang:ink_metadata
      credentials:
        username: _json_key
        password: ${{ secrets.GOOGLE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Solidity files
        run: |
          solang compile --target substrate ./contracts/solidity/test/*.sol -o ./contracts/
          solang compile --target substrate ./contracts/solidity/*.sol -o ./contracts/
      - uses: actions/upload-artifact@v3
        with:
          name: solidity
          path: ./contracts/*.wasm ./contracts/*.contract
  build-ink:
    runs-on: ubuntu-22.04
    container:
      image: paritytech/contracts-ci-linux:production
    steps:
      - uses: actions/checkout@v3
      - name: Build System contracts
        run: |
          for f in *; do
            if [ -d "$f" ]; then
              echo "building $f"
              cargo +nightly contract build --release --manifest-path=./$f/Cargo.toml
              cp ./$f/target/ink/$f.contract ../
            fi
          done
        working-directory: contracts/system-contracts
      - uses: actions/upload-artifact@v3
        with:
          name: ink
          path: ./contracts/*.wasm ./contracts/*.contract
  integration-tests-generic-clients:
    runs-on: ubuntu-22.04
    needs:
      - build-solidity
      - build-ink
    steps:
      - uses: actions/checkout@v3
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: actions/download-artifact@v3
        with:
          name: solidity
          path: ./contracts/
      - uses: actions/download-artifact@v3
        with:
          name: ink
          path: ./contracts/
      - name: start laguna-chain:devnet
        run: docker run -d -p 9944:9944 us-docker.pkg.dev/laguna-chain/laguna-chain/laguna-chain:0.1.2_evm_compat --dev --ws-external
      - name: Run tests
        run: cargo test generic_client -- --test-threads=1
        working-directory: subxt-tests
  integration-tests-eth-clients:
    runs-on: ubuntu-22.04
    needs:
      - build-solidity
      - build-ink
    steps:
      - uses: actions/checkout@v3
      - name: Login to GAR
        uses: docker/login-action@v2
        with:
          registry: us-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: actions/download-artifact@v3
        with:
          name: solidity
          path: ./contracts/
      - uses: actions/download-artifact@v3
        with:
          name: ink
          path: ./contracts/
      - name: start laguna-chain:devnet
        run: docker run -d -p 9944:9944 us-docker.pkg.dev/laguna-chain/laguna-chain/laguna-chain:0.1.2_evm_compat --dev --ws-external
      - name: Run tests
        run: cargo test eth_client -- --test-threads=1
        working-directory: subxt-tests
